apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab126deploy
  labels:
    app: lab126deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab126deploy
  template:
    metadata:
      name: lab126deploy
      labels:
        app: lab126deploy
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: lab126deploy
spec:
  selector:
    app: lab126deploy
  ports:
    - protocol: TCP
      port: 80
      nodePort: 32567
  type: NodePort
