# Securing Network Traffic
apiVersion: v1
kind: Namespace
metadata:
  name: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: access
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lab127
  namespace: restricted
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: access
      ports:
        - protocol: TCP
          port: 80
