apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lab9-allow-sleepybox1
  namespace: restricted
spec:
  podSelector:
    matchLabels: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
          podSelector:
            matchLabels:
              app: sleepybox1
