apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: my-static-pod
  name: my-static-pod-cluster3-controlplane1
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 80
  selector:
    run: my-static-pod
  type: NodePort
status:
  loadBalancer: {}
